### ISSUE TITLE
array.clear() 

### ISSUE THREAD

**Issue by spencersalazar** [spencersalazar/chuck#13]
The following code:

```
string a[3];
<<< a.cap() >>>;
a.clear();
<<< a.cap() >>>;
```

prints:
    3 :(int)
    3 :(int)

shouldnt clear() completely empty the array?

**Comment by heuermh** [comment]
For what it is worth, I use `a.size(0);` instead of `a.clear();`

https://github.com/heuermh/lick/blob/master/ArrayList.ck#L37

**Comment by spencersalazar** [comment]
Ah yes, thanks for pointing that out -- thats what I do to and it works well. I suppose the bug in this case is more that the intended functionality and purpose of array.clear() is, well, unclear.
