### ISSUE TITLE
Add constrain and lerp methods to Std or Math

### ISSUE THREAD

**Issue by heuermh** [spencersalazar/chuck#33]
The Processing language provides methods `constrain()` and `lerp()` that I often find useful.

`constrain()` reference
http://processing.org/reference/constrain_.html

`lerp()` reference
http://processing.org/reference/lerp_.html

These are also implemented in LiCK in Constrain and Interpolate classes as static methods

https://github.com/heuermh/lick/blob/master/Constrain.ck
https://github.com/heuermh/lick/blob/master/Interpolate.ck

It would be great if these could be added to the Std or Math libraries in ChucK.

**Comment by spencersalazar** [comment]
Ok -- this is added in ccrma/chuck@0604f615af19fbe00382389dd059140b7d2db9c4

**Comment by spencersalazar** [comment]
(Though with slightly different names)

**Comment by heuermh** [comment]
looks great, thanks @spencersalazar
