### ISSUE TITLE
Can't build with XCode

### ISSUE THREAD

**Issue by aknuds1** [spencersalazar/chuck#41]
I can't seem to build ChucK with XCode due to a compilation error, in lo_types_internal.h: `/Users/arve/Projects/chuck/src/lo/lo_types_internal.h:37:10: 'lo/lo_osc_types.h' file not found`. I am able to build with make on the commandline on the other hand.

**Comment by spencersalazar** [comment]
Hey Arve,

This has been fixed, though the primary ChucK repo is now at https://github.com/ccrma/chuck, so you will need to look there for the latest! Also, in general, the included makefiles are the preferred build system for ChucK, while the Xcode project sometimes lags behind. 

Thanks,
spencer

**Comment by heuermh** [comment]
Hello Spencer,

Is there a good way to copy the issues from
https://github.com/spencersalazar/chuck/issues over to the new primary
repo, or are they fine where they are for now?

Thanks,

   michael

**Comment by spencersalazar** [comment]
It would be nice to have the issues copied over, but I dont know of a way to do that automatically. I think its fine to leave them where they are, and I will keep an eye out on both repo issue trackers. Not perfect but its better than copying each one over by hand.
